grpc_cc_test(
    name = "activity_test",
    srcs = ["activity_test.cc"],
    external_deps = ["gtest"],
    language = "c++",
    uses_polling = False,
    deps = [
        "//:activity",
        "//:join",
        "//:promise",
        "//:seq",
        "//:wait_set",
    ],
)


