name: Happy Pancakes
on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize, ready_for_review, auto_merge_enabled, auto_merge_disabled]
  status: {}
  check_run:
    types: [created, completed]
  check_suite: 
    types: [created, completed]
jobs:
  check_status:
    name: Check Status
    runs-on: ubuntu-latest
    steps:
      - name: Check Status
        uses: actions/github-script@v4
        with:
          script: |
            let pull = await github.pulls.get({
              owner: "grpc",
              repo: "grpc",
              pull_number: ${{ github.event.pull_request.number }}
            });
            for (var i = 0; i < pull.data.labels.length; i++) {
              let label = pull.data.labels[i];
              if (label.name == "force-merge") {
                console.log("Saw force-merge label");
                return;
              }
            }
            let statuses = await github.repos.listCommitStatusesForRef({
              owner: "grpc",
              repo: "grpc",
              ref: "${{ github.sha }}"
            });
            need = new Set();
            need.add("Bazel Basic build for C/C++");
            need.add("Portability Tests Linux [Build Only] (internal CI)");
            console.log(statuses);
            for (var i = 0; i < statuses.data.length; i++) {
              let status = statuses.data[i];
              if (status.state == "success") {
                need.delete(status.context);
              }
            }
            if (need.size == 0) {
              return;
            }
            console.log(need);
            core.setFailed("Waiting for: " + [...need].join(', '));

