name: test-test-test
on: [push]
jobs:
  PRAutoFix:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: True
          fetch-depth: 0
      # Run the things!
      - name: pfft
        run: |
          cd ${{ github.workspace }}
          git remote add upstream https://github.com:grpc/grpc.git
          git fetch upstream/master
          git diff upstream/master HEAD --name-only
